// Generated by BuildPilot from the validated call transcript for AL NABOODAH TRAVEL & TOURISM AGENCIES LLC.
// Do not hand-edit business data here across rebuilds — update the source
// requirements and regenerate instead. See src/types/site-config.ts (starter
// template) for the full SiteConfig shape (cinematic or plain variant) and
// docs/DEVIN_3D_WEBSITE_SPEC.md for how each field is used.
import type { SiteConfig } from "./types/site-config";

export const siteConfig: SiteConfig = {
  "variant": "plain",
  "businessName": "AL NABOODAH TRAVEL & TOURISM AGENCIES LLC",
  "purpose": "Travel and tours agency offering desert safaris, city tours, dhow cruises, and holiday packages abroad.",
  "targetAudience": "Tourists visiting Dubai and local residents booking weekend trips or holiday packages abroad.",
  "contact": {},
  "palette": {
    "background": "#F6EEE2",
    "surface": "#FFFFFF",
    "text": "#1A1A1A",
    "muted": "#7A6A50",
    "accent": "#FF8C00",
    "accentHover": "#FFB347"
  },
  "enquirySection": {
    "id": "enquiry",
    "eyebrow": "Start planning your next trip",
    "heading": "Enquire about tours and packages",
    "body": "Tell us your travel dates, interests, and group size. We’ll tailor options and confirm availability.",
    "submitLabel": "Send enquiry",
    "enquiryTypes": [
      "General Enquiry",
      "Book a Tour",
      "Custom Itinerary",
      "Group Booking"
    ],
    "disconnectedMessage": "Form submission is not connected yet.",
    "consentLabel": "By submitting this form you agree to be contacted regarding your enquiry."
  },
  "navigation": [
    {
      "label": "Highlights",
      "href": "#highlights"
    },
    {
      "label": "Enquire",
      "href": "#enquiry"
    }
  ],
  "hero": {
    "eyebrow": "Desert safaris, city tours, and dhow cruises",
    "heading": "Experience Dubai and beyond with warm, adventurous travel",
    "body": "AL NABOODAH Travel & Tourism Agencies LLC offers desert safaris, city tours, dhow cruises, and complete holiday packages. We provide hotel pickup and drop-off seven days a week for a seamless travel experience, whether you’re exploring Dubai or planning a trip abroad.",
    "primaryCta": {
      "label": "Book Your Tour",
      "href": "#enquiry"
    },
    "secondaryCta": {
      "label": "Explore Packages",
      "href": "#highlights"
    }
  },
  "highlightsSection": {
    "id": "highlights",
    "eyebrow": "Our Experiences",
    "heading": "What we offer",
    "body": "From thrilling desert safaris to immersive city tours, serene dhow cruises, and fully planned holiday packages, we tailor experiences for holidays and weekend getaways.",
    "items": [
      {
        "name": "Desert Safaris",
        "description": "Morning and evening safaris across Dubai’s golden dunes with expert guides and memorable experiences."
      },
      {
        "name": "City Tours",
        "description": "Curated routes through Dubai’s neighborhoods, landmarks, and hidden gems for all interests."
      },
      {
        "name": "Dhow Cruises",
        "description": "Relaxing harbor cruises aboard traditional wooden dhows with onboard hospitality."
      },
      {
        "name": "Holiday Packages",
        "description": "Turn-key itineraries for overseas holidays, including flights, accommodation, and experiences."
      },
      {
        "name": "Hotel Pickup and Drop-Off",
        "description": "Convenient transfers to and from your hotel, available seven days a week."
      }
    ]
  }
} satisfies SiteConfig;
